apiVersion: batch/v1
kind: Job
metadata:
  name: camunda-zbctl-deploy
  labels:
    type: camunda-backup-restore
spec:
  template:
    spec:
      containers:
      - name: zbctl-deploy
        image: upgradingdave/zbctl
        command: ["zbctl", "--host", "camunda-zeebe-gateway", "--insecure", "deploy", "/models/CamundaProcess.bpmn"]
        volumeMounts:
        - name: models
          mountPath: /models/CamundaProcess.bpmn
          subPath: CamundaProcess.bpmn
          readOnly: true
      volumes:
      - name: models
        configMap:
          name: models
      restartPolicy: Never
