apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: camunda-application
  namespace: default
  labels:
    service: camunda8
    category: application
    release: prometheus
spec:
  groups:
    - name: camunda-application
      rules:
        - alert: CamundaApplicationPendingIncidents
          expr: zeebe_pending_incidents > 0
          labels:
            service: camunda8
            category: application
            severity: high
            priority: P2
          annotations:
            summary: Pending incidents exist
            description: zeebe_pending_incidents > 0 indicates unresolved incidents in the cluster.

        - alert: CamundaApplicationJobWorkerBacklog
          expr: max_over_time(executor_queued_tasks{name="zeebe_client_thread_pool"}[5m]) >= 40
          for: 20m
          labels:
            service: camunda8
            category: application
            severity: medium
            priority: P3
          annotations:
            summary: Job worker/custom connector backlog high
            description: executor_queued_tasks for Zeebe client thread pool >= 40 for 20m.