global:
  security:
    allowInsecureImages: true

identityKeycloak:
  postgresql:
    image:
      repository: bitnamilegacy/postgresql
      tag: 15.10.0-debian-12-r2

connectors:
  enabled: false

operate:
  env:
  - name: CAMUNDA_OPERATE_BACKUP_REPOSITORY_NAME
    value: "operate-backup"

optimize:
  enabled: false

tasklist:
  env:
  - name: CAMUNDA_TASKLIST_BACKUP_REPOSITORY_NAME
    value: "tasklist-backup"

zeebe-gateway:
  replicas: 1
  env:
  - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
    value: none
# Backup
zeebe:
  env:
  - name: SPRING_PROFILES_INCLUDE
    value: "backup"
  extraConfiguration:
    application-backup.yaml: |
      zeebe:
        broker:
          data:
            backup:
              enabled: true
              store: S3
              s3:
                bucketName: camunda
                forcePathStyleAccess: true
                endpoint: http://minio:9000
                accessKey: minioadmin
                secretKey: minioadmin
                region: us-east-1
                basePath: zeebe

elasticsearch:
  sysctlImage:
    repository: bitnamilegacy/os-shell
  copyTlsCerts:
    image:
      repository: bitnamilegacy/os-shell
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  master:
    masterOnly: false
    replicaCount: 1
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0
  image:
    repository: bitnamilegacy/elasticsearch
    tag: 8.15.4
  global:
    kibanaEnabled: false
  initScripts:
    init-keystore.sh: |
      #!/bin/bash
      set -e

      echo "Adding S3 access keys to Elasticsearch keystore..."

      # Add S3 client default keys to the keystore
      echo "$S3_SECRET_KEY" | elasticsearch-keystore add -f -x s3.client.default.secret_key
      echo "$S3_ACCESS_KEY" | elasticsearch-keystore add -f -x s3.client.default.access_key

  extraEnvVars:
    - name: S3_SECRET_KEY
      value: minioadmin
    - name: S3_ACCESS_KEY
      value: minioadmin