apiVersion: batch/v1
kind: Job
metadata:
  name: camunda-es-snapshot-minio-job
  labels:
    type: camunda-backup-restore
spec:
  template:
    spec:
      containers:
      - name: es-snapshot
        image: curlimages/curl
        envFrom:
        - configMapRef:
            name: camunda-script-config
        command: ["/bin/sh"]
        args:
        - -c
        - |
          #!/bin/sh
          set -e

          # Define base paths
          basePaths=$SNAPSHOT_REPOSITORIES
          
          # Define bucket name
          bucket=$MINIO_BUCKET

          # MinIO specific settings
          endpoint=$MINIO_ENDPOINT

          # Iterate over each bucket name to register it as a snapshot repository without specifying access and secret keys
          for basePath in $basePaths; do
            curl --fail -X PUT "http://$ELASTIC_ENDPOINT/_snapshot/$basePath" -H 'Content-Type: application/json' -d '
            {
              "type": "s3",
              "settings": {
                "bucket": "'"$bucket"'",
                "endpoint": "'"$endpoint"'",
                "protocol": "http",
                "compress": true,
                "client": "default",
                "path_style_access": true,
                "base_path": "'"$basePath"'"
              }
            }'
            echo "Repository $basePath registered with MinIO using keystore credentials."
          done
      restartPolicy: OnFailure