global:
  identity:
    auth:
      # Disable the Identity authentication for local development
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false

optimize:
  enabled: false

connectors:
  enabled: false

identity:
  enabled: false

identityKeycloak:
  enabled: false

postgresql:
  enabled: false

orchestration:
  migration:
    data:
      enabled: true
  security: # https://docs.camunda.io/docs/next/components/concepts/access-control/authorizations/
    authentication:
      method: basic
      unprotectedApi: true
  replicas: 1
  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"
  pvcSize: 10Gi

elasticsearch:
  image:
    tag: 8.18.0
  master:
    replicaCount: 2